### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by rstub** [rstub/swephRdata#1]
The data files in this package can be used with other programs as well. Should the package be renamed? Suggestions:

* DE431SEdata
* DE431SE
* SWIEPH
* SwissEphemeris

**Comment by vreijs** [comment]
Just another thought reading the description of Swiss Ephermeris package (https://www.astro.com/swisseph/swephinfo_e.htm):
"The Swiss Ephemeris is based upon the planetary and lunar ephemeris DE431 developed by NASA's Jet Propulsion Laboratory. It covers the time range 13201 BC to AD 17191. These data have been further compressed with sophisticated compression techniques developed by Astrodienst. This compressed ephemeris reproduces the JPL data with 0.001 arcseconds precision. The Swiss Ephemeris files for the planets without the Moon take up 27 Mb disk space, the files for the Moon take up 70 Mb, totally 97 Mb disk space. The original JPL file takes up 2788 Mb disk space."

SECompDE431 (Swiss Ephemeris' compressed DE431)

**Comment by vreijs** [comment]
i think we don't need the 'R' as the SWIEPH is fully independent of R

**Comment by vreijs** [comment]
Any preference on naming here?

**Comment by rstub** [comment]
I like "SwissEphemeris" since it is human readable instead of some (more or less) cryptic abbreviation.

**Comment by vreijs** [comment]
Lets go with that, then.

**Comment by rstub** [comment]
I guess I have to be realistic here: Changing the name takes some time. Time that I cannot spend on this at the moment. And even though the data in the package does not relate to R, it is still an R package. I would be surprised if anyone would want to use this package without also using swephR.

**Comment by vreijs** [comment]
Agree. Lets kepe it as it is.
