### ISSUE TITLE
Cannot get swephR to use Swiss Ephemeris instead of Moshier

### ISSUE THREAD

**Issue by batuozdemir** [rstub/swephRdata#4]
Hi,
I have the swephRdata package installed, and when I set 
`iflag <- SE$FLG_SWIEPH + SE$FLG_SPEED`
it still uses the Moshier ephemeris. 

I tried using the swe_set_ephe_path function
`swe_set_ephe_path(path = "/Users/user/Library/R/4.0/library/swephRdata/ephemeris")`
but no luck.

Could you help me with this please?
Thanks

**Comment by rstub** [comment]
I am sorry for overlooking this. Let's discuss it at https://github.com/rstub/swephR/issues/61.
